### ISSUE TITLE
NNBD - null values with dynamic isn't a problem?

### ISSUE THREAD

**Issue by marcobraghim** [dart-lang/language#1022]
Hey guys, sorry if this was discussed before. I just started to follow null-safety subjects. The possibility of create a variable dynamic that can always have a null value may seems too much attractive to some people instead of really use nnbd as right.

```dart
String bar = null; // Doesn't work with nnbd
var foo = null; // It works with nnbd
```

Wont it start to produce too much code with bad type usage, mainly by beginners?

**Comment by Cat-sushi** [comment]
[Customizing static analysis | Dart](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks "Customizing static analysis | Dart")

analysis_options.yaml
```yaml:
analyzer:
  strong-mode:
    implicit-dynamic: false
```

**Comment by nickroeker** [comment]
My struggle with this is runtime implications (which is maybe what you're getting at), but also that the analyzer doesn't seem to be aware of this case. DartPad link for discussion: https://nullsafety.dartpad.dev/7f6510869dcf7ac21aa47e4ddd16d952

I can have a function that takes a non-nullable,

```dart
bool isListEmptyNNBD(List<String> strList) {
    return strList.isEmpty;
}
```

It's not doing a null check because the argument, `strList`, is non-nullable. As a developer here, I've made a design decision that I should never expect a null here and that the analyzer/compiler is assuring this for me on all calls. I can't guarantee that I will personally be perfect at this (which is why I'm choosing NNBD), and I also cannot expect that package users/coworkers would be either.

However, it's perfectly valid to throw a `null` at it via `dynamic`.

```dart
dynamic sneakyNull = null;
isListEmpty(sneakyNull); // Uh oh! This is valid code, but throws!
```

DartPad isn't always showing an error for some reason, but when it does I get...
```
Error: Expected a value of type 'List<String>', but got one of type 'Null'
```

Locally, this is what I get on 2.9.0-14.1.beta:
```
Unhandled exception:
type 'Null' is not a subtype of type 'List<String>'
#0      main (file:///home/redacted/nndb_test.dart:4:25)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
So you'd think "Ah, ok, even if it's NNBD, I should still check for null for absolute safety". If you try this, the analyzer will happily tell you this is pointless, even though its assertion is demonstrably incorrect:

```"The operand can't be null, so the condition is always false - line nnn"```

You can see this in the linked DartPad example, function name `isListEmptyNNBDButNotActually`.

I'm not sure what to make of this. `dynamic` has some very valid use-cases, but intentionally drops type checks which is an awkward occurrence with NNBD (given that null is essentially a type to my understanding).

I don't have a recommendation, just thought I'd expand on why I find this weird and hope it's relevant to the OP. I ran into this when modifying unit tests for an API that I changed to be compatible with NNBD. Perhaps it's too contrived, but I think I can see how this would naturally happen in real-world development.

**Comment by leafpetersen** [comment]
@marcobraghim There are some discussions underway about how to deal with `var`, in part [here](https://github.com/dart-lang/language/pull/1009).  It is definitely the case right now that you can end up with `dynamic` in unexpected places, which can be surprising.  One way or the other, we will be continuing to push on the set of `--strict` options in the next few quarters for users who want stricter checking.

**Comment by leafpetersen** [comment]
@nickroeker Dart 2 preserved the Dart 1 behavior allowing implicit downcasts.  In the Null Safety release, we will eliminate this entirely, except, as you observe, for `dynamic`.  It will still be valid to downcast from `dynamic` to any type.  This can currently be disable using the `--no-implicit-cast` analyzer option, but note that we plan to migrate this to a more general set of `--strict` flags in the coming quarters.

**Comment by samuelstroschein** [comment]
The discussed issue just happened to me in production.

The null safety migration caused a major bug because I, or the dart migrate tool, dropped a null check in one method which expected a non-nullable map of type <dynamic, dynamic>. 

Here is how to reproduce the issue: 
```Dart

void processMap(Map data){
  print(data['y']);
}


void main() {
  Map x = {};
  processMap(x['nonExistentKey']);
}
```
which will throw:
```
Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'Map<dynamic, dynamic>'
```

A null error should not be possible with "sound" null safety. 

### A possible solution?
Why is `dynamic` not null safe i.e. `dynamic` and `dynamic?`. The default inference for a "dynamic" type could then be dynamic? which should warn or raise an exception in the example above.

**Comment by SuporteSysrs01** [comment]
In my application, I use a LOT of JSON (`Map<String, dynamic>`) types.

After migrating to null safety, my biggest issue is the analyzer not telling me that accessing that map could return `null`. Sure, changing it to `Map<String, Object?>` works, and it warns me about it potentially being `null`, but now I have to explicitly cast _every. single. time._ I try to access a value from it. Which makes me choose between "Do I want to have 20 casts in the following block or do I not want null safety?".

I can't understand why disabling type checking also has to disable null checking, having `dynamic` and `dynamic?` would solve all the issues I have with null safety, as it would warn me about it potentially being null but also implicitly casting if it isn't.

**Comment by jakemac53** [comment]
You can avoid implicit casts from dynamic with this setting in analysis_options.yaml, and I would very strongly encourage using it:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

This would make the code above give the following error `The argument type 'dynamic' can't be assigned to the parameter type 'Map<dynamic, dynamic>'`.

**Comment by SuporteSysrs01** [comment]
> You can avoid implicit casts from dynamic with this setting in analysis_options.yaml

Actually, I _do_ want implicit casts. The data from every class in my application comes from an API, thus, every class has a `fromJSON()` constructor in it. Disabling implicit casts (or using `Object?`) would result in the following (for every class in my application):

![image](https://user-images.githubusercontent.com/87761804/163438326-d3c54c64-c236-4b34-8ced-a4178ccfd496.png)

I really don't like having to add `as String`, `as int`, `as double` to every line. It doesn't make my code safer, as it would still result in a runtime exception if it fails, but I would **love** to have a warning telling me that it could potentially be `null`, and making me go there and just add a ! to `map['crn_credencial']!` if it was being assigned to a non-nullable, for example.

There were many times that I used a `dynamic` map to avoid having to explicitly cast many lines, but forgot that it could potentially be `null`, and having myself go there an add a `!` would have avoided that.

**Comment by rrousselGit** [comment]
What about an extension on Map:

```dart
extension<Key, Value> on Map<Key, Value> {
  R? getCast<R>(Key key) => this[key] as R?;
}
```

Then do:

```dart
class Foo {
  Foo.fromJson(Map<String, Object?> json):
    count = json.getCast<int>()!;

  final int count;
}
```

**Comment by SuporteSysrs01** [comment]
> What about an extension on Map

I tried your code in DartPad, and although I thought it would work, there still no warning, looks like type-inference wasn't able to handle it (neither in the direct assignments in my code):

![image](https://user-images.githubusercontent.com/87761804/163442872-8c843045-be4c-4d14-a4e7-78089e27a18d.png)

Tried to fiddle with the `?` but to no success. It still gives me a runtime exception: `Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'int'`. Explicitly adding the generic type to it makes it warn me, but in that case it wouldn't be better than just adding a cast in the end.

> There is also the [cast_nullable_to_non_nullable](https://dart-lang.github.io/linter/lints/cast_nullable_to_non_nullable.html) lint

Looks like that would be the one to save me haha

**Comment by rrousselGit** [comment]
> I tried your code in DartPad, and although I thought it would work, there still no warning, looks like type-inference wasn't able to handle it (neither in the direct assignments in my code):

Dartpad is the problem.

You'll get a warning in a typical application with implicit-cast disabled


![Screenshot 2022-04-14 at 20 04 31](https://user-images.githubusercontent.com/20165741/163450447-8a885230-6c01-4b3f-a64d-4d464bf2a441.png)

**Comment by SuporteSysrs01** [comment]
> Dartpad is the problem.
> 
> You'll get a warning in a typical application with implicit-cast disabled

Yup! Sorry, I had implicit-cast enabled when I tried it, after disabling it your extension works like a charm! Thank you so much!

Also, your implementation inspired me to reimplement the base `Map` class (just like the `DelegatingMap` does) and adding that `getCast` method directly to it while also deprecating the usage of the `[]` operator (would be nice to have a generic type to it so I could turn _that_ into the `getCast` method but that's another thing), so I would be 100% sure that nobody would try to use it directly.
