### ISSUE TITLE
enums to implement Comparable

### ISSUE THREAD

**Issue by mleonhard** [dart-lang/language#1836]
When enums implement [`Comparable`](https://api.dart.dev/stable/dart-core/Comparable-class.html), we can sort them and use them in sorted collections without boilerplate.

```dart
// example.dart
import 'dart:collection' show SplayTreeMap, SplayTreeSet;

enum MyEnum { One, Two }

void main() {
  final items = [MyEnum.Two, MyEnum.One];
  // Unhandled exception:
  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>' in type cast
  // #0      ListMixin._compareAny (dart:collection/list.dart:360:33)
  // dart-lang/sdk#1      Sort._insertionSort (dart:_internal/sort.dart:69:36)
  // dart-lang/sdk#2      Sort._doSort (dart:_internal/sort.dart:58:7)
  // dart-lang/sdk#3      Sort.sort (dart:_internal/sort.dart:33:5)
  // dart-lang/sdk#4      ListMixin.sort (dart:collection/list.dart:356:10)
  // dart-lang/sdk#5      main (file:///example.dart:5:9)
  // dart-lang/sdk#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // dart-lang/sdk#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  items.sort();

  // This ugly boilerplate works.
  items.sort((a, b) => a.index.compareTo(b.index));

  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>'
  // #0      _dynamicCompare (dart:collection/splay_tree.dart:279:65)
  // dart-lang/sdk#1      _SplayTree._splay (dart:collection/splay_tree.dart:86:15)
  // dart-lang/sdk#2      SplayTreeSet._add (dart:collection/splay_tree.dart:884:19)
  // dart-lang/sdk#3      SplayTreeSet.add (dart:collection/splay_tree.dart:881:26)
  // dart-lang/sdk#4      main (file:///example.dart:24:14)
  // dart-lang/sdk#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // dart-lang/sdk#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  final SplayTreeSet<MyEnum> orderedSet = SplayTreeSet();
  orderedSet.add(MyEnum.One);
  orderedSet.add(MyEnum.Two);

  // This ugly boilerplate works.
  final SplayTreeSet<MyEnum> orderedSet2 =
      SplayTreeSet((a, b) => a.index.compareTo(b.index));
  orderedSet2.add(MyEnum.One);
  orderedSet2.add(MyEnum.Two);

  // Unhandled exception:
  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>'
  // #0      _dynamicCompare (dart:collection/splay_tree.dart:279:65)
  // dart-lang/sdk#1      _SplayTree._splay (dart:collection/splay_tree.dart:86:15)
  // dart-lang/sdk#2      SplayTreeMap.[]= (dart:collection/splay_tree.dart:408:16)
  // dart-lang/sdk#3      main (file:///example.dart:22:13)
  // dart-lang/sdk#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // dart-lang/sdk#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  final SplayTreeMap<MyEnum, String> orderedMap = SplayTreeMap();
  orderedMap[MyEnum.One] = 'one';
  orderedMap[MyEnum.Two] = 'two';

  // This ugly boilerplate works.
  final SplayTreeMap<MyEnum, String> orderedMap2 =
      SplayTreeMap((a, b) => a.index.compareTo(b.index));
  orderedMap2[MyEnum.One] = 'one';
  orderedMap2[MyEnum.Two] = 'two';
}
```

**Comment by cheenbee** [comment]
items.sort((a, b) => a.index - b.index);

**Comment by mateusfccp** [comment]
I feel like this can be closed, as for a long time now we are able to implement interfaces in enums:

```dart
enum MyEnum implements Comparable<MyEnum> {
  One,
  Two;

  @override
  int compareTo(MyEnum other) => index - other.index;
}
```

If you want something more generic to apply to all enums:
```dart

mixin EnumIndexComparable<T extends Enum> on Enum implements Comparable<T> {
  @override
  int compareTo(T other) => index - other.index;
}

enum MyEnum with EnumIndexComparable<MyEnum> {
  One,
  Two;
}
```
