### ISSUE TITLE
Type arguments for generic List, Map, Set

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#2212]
I'm looking at the following part of the specification: If the parameter type specifies a generic type argument, it must be one of the allowed parameter types or Object, recursively. But I think the code that constructs arguments on the remote side does not support type arguments, so it always creates List<Object?> for example, and if the parameter requires List<int> the invocation fails.

```dart
macro class ArgumentsTextMacro implements ClassTypesMacro {
  final List<int> foo;

  const ArgumentsTextMacro(this.foo);

  FutureOr<void> buildTypesForClass(clazz, builder) {
    builder.declareType(
      'x',
      DeclarationCode.fromString(
        "const x = 'foo: $foo\\n';",
      ),
    );
  }
}
```
Results in
```
Expected: empty
    Actual: 'Unknown(annotation: 0, message: RemoteException: type \'List<Object?>\' is not a subtype of type \'List<int>\' of \'foo\'\n'
              '\n'
              '#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:105:68)\n'
              '#1      Function._apply (dart:core-patch/function_patch.dart:11:73)\n'
              '#2      Function.apply (dart:core-patch/function_patch.dart:34:12)\n'
              '#3      _instantiateMacro (package:test/arguments_text.dart.macro)\n'
              '#4      _handleMessage (package:test/arguments_text.dart.macro)\n'
              '#5      main.<anonymous closure>.<anonymous closure> (package:test/arguments_text.dart.macro)\n'
```

**Comment by scheglov** [comment]
I also expected to get a similar exception for `List<Object>` - we create `List<Object?>`, right? But somehow it works.

This program has a compile-time error.
```dart
void f(List<Object> a) {}

main() {
  f(<Object?>[0]);
}
```

**Comment by jakemac53** [comment]
> I also expected to get a similar exception for `List<Object>` - we create `List<Object?>`, right? But somehow it works.

Yeah I don't understand how that is working... unless your macro is opted out of null safety?

**Comment by scheglov** [comment]
Well, we compile macros with `vm.VmTarget(fe.TargetFlags(enableNullSafety: true))`, so this code fails to run:
```dart
  FutureOr<void> buildTypesForClass(clazz, builder) {
    int a = null;
    print(a);
```
Throws:
```
  Expected: empty
    Actual: 'Unknown(annotation: 0, message: RemoteException: error: /home/test/lib/arguments_text.dart:10:13: Error: The value \'null\' can\'t be assigned to a variable of type \'int\' because \'int\' is not nullable.\n'
              '    int a = null;\n'
              '            ^\n'
              '\n'
              '#0      executeTypesMacro (package:_fe_analyzer_shared/src/macros/executor/execute_macro.dart)\n'
              '#1      _executeTypesPhase (package:test/arguments_text.dart.macro)\n'
              '#2      _handleMessage (package:test/arguments_text.dart.macro)\n'
              '#3      main.<anonymous closure>.<anonymous closure> (package:test/arguments_text.dart.macro)\n'
```
Maybe something less restrictive for `Function.apply()`? Although this also throws:
```dart
void f(List<Object> a) {}

main() {
  Function.apply(f, [<Object?>[0]]);
}
```

**Comment by jakemac53** [comment]
In general this feature looks a lot harder to implement than I was expecting, going to take some time to figure out a good solution here.

**Comment by jakemac53** [comment]
Note that the type arguments are explicitly a `List<ArgumentKind>` because we want the valid type arguments to be restricted to those types that are supported types of arguments for macro constructors anyways. We can't construct type arguments for arbitrary types.
