### ISSUE TITLE
Issue when combining list spreading, optional chaining, and class extensions

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/language#2251]
I have found an issue when combining list spreading, optional chaining, and class extensions:

```dart
void main() {
  final List<TestClass>? nullList = null;

  // A list with nothing special going on works as expected
  final list1 = [
    TestClass(),
  ];
  print('list1:');
  print(list1.first.value1);
  print(list1.first.value2);

  // Typing the optional chain value fixes the issue
  final list2 = [
    TestClass(),
    ...nullList ?? <TestClass>[],
  ];
  print('list2:');
  print(list2.first.value1);
  print(list2.first.value2);

  // Typing the list fixes the issue
  final list3 = <TestClass>[
    TestClass(),
    ...nullList ?? [],
  ];
  print('list3:');
  print(list3.first.value1);
  print(list3.first.value2);

  // The analyzer has no issues with this, but the code throws an exception
  // The analyzer says the list is of type List<TestClass>
  final list4 = [
    TestClass(),
    ...nullList ?? [],
  ];
  print('list4:');
  print(list4.first.value1);
  print(list4.first.value2);
}

class TestClass {
  int get value1 => 0;
}

extension on TestClass {
  int get value2 => 1;
}
```

```console
list1:
0
1
list2:
0
1
list3:
0
1
list4:
0
Unhandled exception:
NoSuchMethodError: Class 'TestClass' has no instance getter 'value2'.
Receiver: Instance of 'TestClass'
Tried calling: value2
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      main
bin/enum_test.dart:37
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Exited (255)
```

The analyzer has no issues with the given code, but there is an exception when running. Unsure if this is an issue with the analyzer or something else.

**Comment by jakemac53** [comment]
> ```dart
> ...nullList ?? [],
> ```

I would guess that the CFE isn't inferring `<TestClass>[]` for the list on the rhs of the `??` here. Probably a difference between the cfe and analyzer type inference?

cc @johnniwinther
