### ISSUE TITLE
Issue with type inference in constant factory constructors

### ISSUE THREAD

**Issue by SandroMaglione** [dart-lang/language#2869]
Hi,

I found a possible issue while working with constant factory constructors (i.e. `const factory`) [^1].

[fpdart](https://pub.dev/packages/fpdart) defines a constant [factory constructor for the Option type](https://github.com/SandroMaglione/fpdart/blob/e892c8d158cc63c4e6d5b4eebaa95107c708d66a/lib/src/option.dart#L474) as follows:
```dart
  /// Return a [None].
  const factory Option.none() = None<T>;

  /// Return a `Some(a)`.
  const factory Option.of(T t) = Some<T>;
```

We found an issue when the type system tries to infer the generic type in some functions, for example [`map`](https://github.com/SandroMaglione/fpdart/blob/e892c8d158cc63c4e6d5b4eebaa95107c708d66a/lib/src/option.dart#L664):

```dart
Option<B> map<B>(B Function(T t) f) => const Option.none();
```

Returning a `const` using the factory constructor `none()` infers the type as `Option<Never>`. If instead the return is not marked as `const` the return type is `Option<B>` as expected:

<img width="781" alt="Screenshot 2023-02-26 at 18 02 19" src="https://user-images.githubusercontent.com/10065056/221425563-a002b744-bb12-4eab-83b4-ce405747b81a.png">

<img width="735" alt="Screenshot 2023-02-26 at 18 02 37" src="https://user-images.githubusercontent.com/10065056/221425571-9e528998-b8d8-4a49-94bd-c2586a8c8bea.png">

This causes **runtime** issues when working with the result of `map`. For example:

```dart
import 'package:fpdart/fpdart.dart';

Option<String> nonEmptyString(String? s) => Option.fromNullable(s).map(
      (t) => t.trim(),
    );

void main() {
  nonEmptyString(null).alt(() => nonEmptyString('hi'));
}
```

VSCode infers the return type as `Option<String>`:

<img width="923" alt="Screenshot 2023-02-26 at 18 15 39" src="https://user-images.githubusercontent.com/10065056/221425899-c0687ab7-b8b7-43ab-9975-15026d2a67a1.png">

but then when you run the app it fails with the following error:

```shell
Unhandled exception:
type '() => Option<String>' is not a subtype of type '() => Option<Never>' of 'orElse'
#0      None.alt (package:fpdart/src/option.dart)
#1      main (file:///Users/sandromaglione/Development/projects/dart/fpdart/example/src/either/cast.dart:13:24)
cast.dart:13
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

This happens because `map` in the function `nonEmptyString` returns `Option<Never>`, that fails when using [`alt`](https://github.com/SandroMaglione/fpdart/blob/e892c8d158cc63c4e6d5b4eebaa95107c708d66a/lib/src/option.dart#L676) (which calls `orElse` as reported in the error) with a type error.

Is this behaviour expected using `const factory`? Could there be an issue with inference?

[^1]: [PR](https://github.com/SandroMaglione/fpdart/pull/92)

**Comment by lrhn** [comment]
Looks like it's working as intended.

The code
```dart
Option<B> map<B>(B Function(T t) f) => const Option.none();
```
must create a single value from the `const Option.none()` expression, because a `const` expression always evaluates to the same value, which must be a valid return value from the `map` function for *any* binding of `B`.

It can't create an `Option<B>.none()`, because `B` isn't known until runtime, and constants are evaluated at compile-time.
So it chooses `Never` as the only possible type argument.

If you remove the `const`, it doesn't have to create the object until runtime, and it creates a new object for each call, so it can use the `B` as type argument.


What I'd do is to embrace the `Never` and make all `None` values be `Option<Never>`.
```dart
abstract class Option<T> {
  static const Option<Never> none = const None();

  const factory Option.value(T value) = Some<T>;

  factory Option.fromNullable(T? value) => 
      value == null ? none : Some<T>(value);

  Option<R> map<R>(R Function(T) convert);
}

class Some<T> implements Option<T> {
  final T value;
  const Some(this.value);
  Option<R> map<R>(R Function(T) convert) => Option<R>.value(convert(value));
}

class None implements Option<Never> {
  const None();
  Option<R> map<R>(R Function(Never) convert) => this;
}
```
That is, deliberatly use a `Never` type argument to `Option` on `None`, so it can be used as any option type,
and make sure the methods work too. As long as the type parameter occurs only covariantly, like it does here for `map`,
it should work.

**Comment by SandroMaglione** [comment]
@lrhn thanks for the suggestions, we opted for using `Never`

Would it be possible for the type system to catch this error at compile time instead of failing at runtime?

**Comment by eernstg** [comment]
As @lrhn mentioned, the fundamental issue is that `Option` uses the type variable `T` in a non-covariant position, in the type of the formal parameter `orElse`.

However, the use of a single instance of `None`, namely the constant `Option.none`, forces covariance to occur basically every single time `Option` is used for anything meaningful.

This can be avoided if we adopt a different trade-off: In order to "remember" the type argument even in the case where a value turns out to be `None`, we will give the class `None` the same type argument as `Some`, and then create instances of `None<T>` for the relevant `T` when needed:

```dart
abstract class Option<T> {
  const factory Option.value(T value) = Some<T>;

  factory Option.fromNullable(T? value) {
    if (value == null) return None();
    return Some<T>(value);
  }

  Option<R> map<R>(R Function(T) convert);
  Option<T> alt(Option<T> orElse());
}

class Some<T> implements Option<T> {
  final T value;
  const Some(this.value);
  Option<R> map<R>(R Function(T) convert) => Option<R>.value(convert(value));
  Option<T> alt(Option<T> orElse()) => this;
  String toString() => 'Some<$T>($value)';
}

class None<T> implements Option<T> {
  const None();
  Option<R> map<R>(R Function(T) convert) => None();
  Option<T> alt(Option<T> orElse()) => orElse();
  String toString() => 'None<$T>()';
}

Option<String> nonEmptyString(String? s) =>
    Option.fromNullable(s).map((t) => t.trim());

void main() {
  print(nonEmptyString(null).alt(() => nonEmptyString('hi')));

  Option<Object> o = Some<String>('Hello!');
  print(o.alt(() => Some(1))); // Throws.
}
```

Running this program, we can see that the invocation of `alt` will now succeed. However, the issue with the `orElse` parameter still exists, as shown in the last two lines of `main`.

We can take one more step if we use the (not yet finished, certainly not yet released) upcoming support for declaration-site variance (#524):

```dart
abstract class Option<inout T> {
  const factory Option.value(T value) = Some<T>;

  factory Option.fromNullable(T? value) {
    if (value == null) return None();
    return Some<T>(value);
  }

  Option<R> map<R>(R Function(T) convert);
  Option<T> alt(Option<T> orElse());
}

class Some<inout T> implements Option<T> {
  final T value;
  const Some(this.value);
  Option<R> map<R>(R Function(T) convert) => Option<R>.value(convert(value));
  Option<T> alt(Option<T> orElse()) => this;
  String toString() => 'Some<$T>($value)';
}

class None<inout T> implements Option<T> {
  const None();
  Option<R> map<R>(R Function(T) convert) => None();
  Option<T> alt(Option<T> orElse()) => orElse();
  String toString() => 'None<$T>()';
}

Option<String> nonEmptyString(String? s) =>
    Option.fromNullable(s).map((t) => t.trim());

void main() {
  print(nonEmptyString(null).alt(() => nonEmptyString('hi')));

  // Option<Object> o = Some<String>('Hello!'); // Compile-time error.
}
```

With this feature, we can mark the type variable of `Option` and its subtypes as invariant. This means that there is no subtype relationship between `Option<T1>` and `Option<T2>` when `T1` and `T2` are different types. Without `inout`, and in particular in current Dart, we have subtype relationships like `Some<String> <: Option<Object>`, which is the root cause that enables the dynamic type error in the previous example. With sound variance, we get an error at the end of `main`, so there's no way we can start doing wrong things with the given `Some<String>`.

So the answer is "Yes, we can make this safer", with two distinct degrees of added safety, but full static safety requires some kind of statically checked variance and we will only have that when/if #524 is adopted.

**Comment by eernstg** [comment]
Yes, if you have #524 and make it `class Option<inout T> ...` then the line `.alt(() => none)` in that example is a compile-time error, because `None<Never>` is not a subtype of `None<String>`.

You can emulate invariant type parameters by some manual work: If you want to have a single invariant type parameter `X` then declare two, say, `X` and `X2`.  `X2` is never used in the body, but it must get the value `T Function(T)` whenever `X` has the value `T`. This means that the corresponding generic type is invariant in `X` (if this has been done consistently). For example:

```dart
abstract class Option<A, B> {
  const factory Option.value(A value) = Some<A, B>;
  const factory Option.none() = None<A, B>;

  factory Option.fromNullable(A? value) {
    if (value == null) return Option<A, B>.none();
    return Some<A, B>(value);
  }

  Option<A, B> alt(Option<A, B> Function() orElse);
}

class Some<A, B> implements Option<A, B> {
  final A value;
  const Some(this.value);
  @override
  Option<A, B> alt(Option<A, B> Function() orElse) => this;
  @override
  String toString() => 'Some<$A, $B>($value)';
}

class None<T, B> implements Option<T, B> {
  const None();
  @override
  Option<T, B> alt(Option<T, B> Function() orElse) => orElse();
  @override
  String toString() => 'None<$T>()';
}

void main() {
  const none = Option<Never, Never Function(Never)>.none();

  print(
    Option<String, String Function(String)>.fromNullable(null)
        .alt(() => none) // <-- Here: Compile-time error.
        .alt(() => const Option.value("world")),
  );
}
```

The compile-time error is that `none` has type `None<Never, Never Function(Never)>`, but the required type is `Option<String, String Function(String)>`. This is exactly the same treatment of `X` as is given to `inout X` (via the detour to `X2`, and the assumption that `X2` has the value `X Function(X)`)
