### ISSUE TITLE
Unwanted Object-inference induced type errors #2

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#3274]
This issue presents a similar issue as the one in https://github.com/dart-lang/language/issues/3156, but one which can't be addressed with statically checked variance. 

Consider the following example:

```dart
void main() {
  final bar = [
    ["a"],
    ["a", "b", "c"],
  ].map(
    (final e) {
      if (e.length == 1) {
        return e.single;
      } else {
        return e;
      }
    },
  ).toList()..sort();
  print(bar);
}
```

The issue here is that the return type of the function passed to `map` is inferred to be `Object`. This, in my opinion, is not very helpful and can lead to accidental runtime exceptions:

```
Unhandled exception:
type 'List<String>' is not a subtype of type 'Comparable<dynamic>' in type cast
#0      ListMixin._compareAny (dart:collection/list.dart:360:50)
#1      Sort._insertionSort (dart:_internal/sort.dart:69:36)
#2      Sort._doSort (dart:_internal/sort.dart:58:7)
#3      Sort.sort (dart:_internal/sort.dart:33:5)
#4      ListMixin.sort (dart:collection/list.dart:356:10)
#5      main (package:humanspec/parser/sine/hele/dart/meta/foo.dart:13:15)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

Such mistakes are easy to make, and other languages have made choices that prevent such errors. Consider, for example, Swift, where returning a String and a List leads to an error at compile time.

```swift
let bar = [["a"], ["a", "b", "c"]]
  .map { e in
      if e.count == 1 {
          return e[0]
      } else {
          return e
      }
  }
  .sorted()
print(bar)
```

```
  error: cannot convert return expression of type '[String]' to return type 'String'
```

I've alluded to a separate analysis step analogous to `implicit-dynamic`, but only for `Object`-related-inferences (e.g. `implicit-object`) in https://github.com/dart-lang/language/issues/3156 which could help prevent such errors. I still think that that is worth considering and could be valuable to Dart users.

**Comment by eernstg** [comment]
You can get the same error in a simpler way:

```dart
void main() {
  ["", 1].sort();
}
```

The point is simply that `sort` with no actual argument will use 


requires list elements whose dynamic type is a subtype of `Comparable<T>` for some `T`, and then each element is only comparable

**Comment by modulovalue** [comment]
It might look like I intended this issue to be about this particular example (that is, the sort method causing a crash), but I meant it to only be an example.

What I wanted to point out is that, in cases like these, one can't rely on the type checker to report that type inference "failed", or in other words, it's not possible to encode the constraint that "Object should never be inferred from two unrelated types". This constraint is useful when, for example, type signatures are being migrated, as any reported violation helps with any such migration.

The observation that this is not an issue in Swift, (and probably most other mainstream languages, see https://github.com/dart-lang/language/issues/3156#issuecomment-1603198957) seems like evidence that this is, in fact, an issue. It appears to definitely go against what most people would have learned to expect. 

I agree that adjusting any core libraries to prevent such issues might not be worth the churn that it could cause and I'm not suggesting this should be done. However, It looks like this is an issue that appears to be preventable in a rather simple way with an additional analysis step, as is already being done for other issues via, for example, [strict-casts](https://github.com/dart-lang/language/blob/main/resources/type-system/strict-casts.md), [strict-raw-types](https://github.com/dart-lang/language/blob/main/resources/type-system/strict-raw-types.md) or [strict-inference](https://github.com/dart-lang/language/blob/main/resources/type-system/strict-inference.md).

**Comment by lrhn** [comment]
A "don't infer `Object`" (and likely not `Object?` either) seems like it could catch mistaken combinations of unrelated types that end up in an upper bound.

I'd normally not be too worried about that, because if you get `Object` as type, you'll find out soon if you try to use it for anything that isn't allowed on all objects, and if it is allowed on all objects, ... maybe it was what you wanted.

You the point a finger to a painful point in the Dart APIs, where Dart 1 APIs did not migrate safely to the Dart 2 type system (and we have some pre-null safety APIs that didn't migrate safely to the null safe type system too).

`List.sort` is simply not safe. If you don't pass a comparator, it will assume that all objects are `Comparable` to each other, and fail at runtime if they aren't. The parameter really should be required. 
(It's just so *convenient* when sorting lists of integers or strings, or comparable objects like `DateTime`. And we don't have a good way to deprecated the *optionality*.)

Or, really, `sort` should be an extension method, not an instance method. Then we can have `sort(Comparator<T>` on `List<T>`, but `sort([Comparator<T>])` on `List<T extends Comparable<T>>`.
(And we don't have a good way to deprecate an instance method, and turning it into an extension method, without hitting people with deprecation warnings that they should really be ignoring, because their code will keep working.)

**Comment by modulovalue** [comment]
(_No, really, I'm not trying to highlight any issues with the `sort` API or statically un-checked variance. I agree that the current API is convenient and I have no issues with the trade-offs that were made._)

---


> A "don't infer Object" (and likely not Object? either) seems like it could catch mistaken combinations of unrelated types that end up in an upper bound.

Exactly!

### implicit-dynamic

Consider how `implicit-dynamic` behaves (_For context, here's the issue that landed implicit-dynamic: https://github.com/dart-lang/sdk/issues/25573_):

If the implicit-dynamic analysis step is not enabled, the following code produces no warnings:

```dart
var someList = [];
```

However, if the `implicit-dynamic` analysis step is enabled, that code produces the following diagnostic:

```dart
// Missing type argument for list literal.
// Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
//             vv
var someList = [];
```

### implicit-object

Now, what if there was an `implicit-object` that makes Object-related inferences an error in a similar way how `implicit-dynamic` turns dynamic-related inferences into an error.

So, without `implicit-object` enabled, the following would be fine:

```dart
void main() {
  ["", 1];
}
```

However, if an `implicit-object` analysis step is enabled, that code would produce the following diagnostic:

```dart
void main() {
// Missing type argument for list literal.
// Try adding an explicit type, or remove implicit-object from your analysis options file.
//vvvvvvv
  ["", 1].sort();
}
```

> I can't immediately see how this could be done in such a way that it would compensate for the inherently type-unsafe Comparable.compare.

an `implicit-object` analysis step would probably not compensate for all unsafe uses of Comparable.compare, but, I feel like, it could prevent a large amount by emitting diagnostics for code that could lead to unsafe uses. This would be an opportunity to double check *why* an Object was inferred.

Does that make sense?

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/2539#issuecomment-1263598300. ;-)

**Comment by modulovalue** [comment]
> Cf. https://github.com/dart-lang/language/issues/2539#issuecomment-1263598300. ;-)

I completely agree with your observation, and I am strongly in favor of having a lint or some analysis step that implements what you have proposed in your comment.
