### ISSUE TITLE
Extension types on typed_data

### ISSUE THREAD

**Issue by curt-weber** [dart-lang/language#3635]
Extension types don't seem to support typed data, for instance `Float64x2`.
There is a restriction that typed_data isn't extended, but that applies to other types like `int`, `double`, which extension types can use.

```
import 'dart:math';
import 'dart:typed_data';

extension type const Point._(Float64x2 point) implements Float64x2 {
  Point(double x, double y) : point = Float64x2(x, y);
  double get distance => sqrt(point.x * point.x + point.y * point.y);
}

void main() => print(Point(0, 0)); // prints null
```
I was checking to see if extension types would be more performant in the case of `Offset`, but using `List<double>` is actually slower from my tests.

**Comment by lrhn** [comment]
That sounds like a bug. You should be able to subtype typed data with extension types.

**Comment by srawlins** [comment]
Are you running this with DDC? For my part, this code:

```dart
import 'dart:math';
import 'dart:typed_data';

extension type const Point._(Float64x2 point) implements Float64x2 {
  Point(double x, double y) : point = Float64x2(x, y);
  double get distance => sqrt(point.x * point.x + point.y * point.y);
}

void main() {
  print('Float64x2: ${Float64x2(0, 0)}');
  print(Point(0, 0));
  print('Point: ${Point(0, 0)}');
}
```

prints this with the Dart VM (3.3.0):

```none
Float64x2: [0.000000, 0.000000]
[0.000000, 0.000000]
Point: [0.000000, 0.000000]
```

and prints this in DartPad (DDC):

```none
Float64x2: [0, 0]
null
Script error.
```

with the following exception in the console:

```none
prints this with the Dart VM (3.3.0):

```none
Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(dartx.toString)')
    at Object.strSafe (operations.dart:1072:38)
    at Object.main$0 [as main] (<anonymous>:69:33)
    at Object.main$ [as main] (<anonymous>:47:10)
    at <anonymous>:106:26
    at Object.execCb (require.js:5:16727)
    at e.check (require.js:5:10499)
    at e.<anonymous> (require.js:5:12915)
    at require.js:5:1542
    at require.js:5:13376
    at each (require.js:5:1020)
    at e.emit (require.js:5:13344)
    at e.check (require.js:5:11058)
    at e.enable (require.js:5:13242)
    at e.init (require.js:5:9605)
    at a (require.js:5:8305)
    at Object.completeLoad (require.js:5:15962)
    at HTMLScriptElement.onScriptLoad (require.js:5:16882)
```

suggesting some weird things: `Point(0, 0)` acts like `null`, except it is a value that doesn't even have a `toString()` method on it?

**Comment by cmkweber** [comment]
Yes, I should have mentioned that was in DartPad. Initially was trying to add it to a `List<Point>` but that wasn’t working and not showing the exception in DartPad for some reason.

**Comment by curt-weber** [comment]
Should this get moved to the `sdk` repo as a bug?
