### ISSUE TITLE
Support debugging Dart projects with compilation errors

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#3651]
## Problem

As the language moves more towards type safety, we have more and more cases where a compilation error can happen.
This is awesome, but can have a debugging drawback.

Consider a large project that's relying a lot on `sealed class` and pattern matching. Adding a new subclass of a such a sealed class could cause hundreds of compilation errors.  
Again, this is expected. The problem is, it prevents debugging the project until **all** errors are fixed.

This is problematic because rather than fixing errors individually, we have to fix them all at once. We therefore cannot guarantee that a fix to one specific error is valid until we have fixed the other errors too.

## Proposal: Support debugging projects even if there are some errors.

The idea would be to have non-syntax errors be ignored when starting the project in debug mode, and have the associated function throw a runtime exception when the error is reached.

For example consider:

```dart
void function() {
  missingIdentifier;
}

void main() {
  print('Hello world'); 
  function();
}
```

Even though in this program `missingIdentifier` used in `function` is never defined, we could allow this program to start.

Then, when running this program in debug mode, it would output:

```
// Before starting the program, the list of all warnings/errors is printed
foo.dart:2:3: Error: Undefined name 'missingIdentifier'.
  missingIdentifier;

// The program then executes normally:
Hello world
Unhandled exception:
ReferenceError: missingIdentifier is not defined
#0      function (file:///Users/remirousselet/dev/rrousselGit/riverpod/foo.dart:2:3)
#1      main (file:///Users/remirousselet/dev/rrousselGit/riverpod/foo.dart:7:3)
```

**Comment by rrousselGit** [comment]
Of course, this is only about debug mode (so JIT). AOT builds should not allow this.

Also, this would only apply to some kind of errors. A missing `}` would likely not be supported, as I assume that breaks too many things.

But things like:
- missing `case` in a switch` 
- trying to assign a String to an int
- trying to reassign a `final` variable
- ...

Those errors likely _could_ be runtime exceptions in debug/JIT mode.

**Comment by mraleph** [comment]
This is how things used to work in Dart 1 days, in Dart 2 days we initially carried some support for running malformed programs: CFE would produce Kernel AST even for malformed programs by replacing parts of the program which failed to compile with special AST node and/or exception throwing. Then VM had to navigate these malformed ASTs and that was _somewhat_ fragile. So we moved away from it and started to refuse to run programs with compilation errors. 

I think it is not unreasonable to support some form of this again, but I would not want VM to need to deal with malformed ASTs. It is too much complexity. We would need to define a set of compile time errors which can become runtime errors - the main requirement here is that "healing away" these compile time errors should not leave AST in a malformed state. The resulting AST should match some valid Dart program. 

There are also some subtle interactions with things like hot reload, as hot reload can't reload some program changes - so allowing some compile time errors might lead you into a state which would require restart to recover. One example of that would be closures - which can't be reloaded. So if you accidentally end up with a closure stored somewhere, which contains a "runtime compile time error" you might not be able to get out of that state without restart.

I don't think this is a language request per se - it is more in the tooling (CFE/VM) space.
