### ISSUE TITLE
Simple fixedList.setAll is not working !! - Theres this simple implementation getting stuck, how could anyone like Flutter/Dart ?

### ISSUE THREAD

**Issue by pk-szt** [dart-lang/language#3732]
final fixedLengthList = List<int>.filled(5, 0); // Creates fixed-length list.
print(fixedLengthList); // [0, 0, 0, 0, 0]
fixedLengthList[0] = 87;
fixedLengthList.setAll(1, [1, 2, 3]);
print(fixedLengthList); // [87, 1, 2, 3, 0]

***
It was working a few days ago. Now it says 

Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Iterable<int>' of 'iterable'
#0      List.setAll (dart:core-patch/array.dart:217:38)

#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by mateusfccp** [comment]
It works perfectly in the latest stable:

<img width="1165" alt="image" src="https://github.com/dart-lang/language/assets/4605213/7f0e003d-e940-47e9-a6f8-2dc18dc7e6d4">

Can you give more details on how to reproduce this issue? Like, which version of Dart are you running? Which OS? Are you running JIT or compiled? Etc.

**Comment by Wdestroier** [comment]
You may not be running the latest stable version, but you can try replacing
```dart
fixedLengthList.setAll(1, [1, 2, 3]);
```
with
```dart
fixedLengthList.setAll(1, <int>[1, 2, 3]);
```
and it should work anyway.
