### ISSUE TITLE
Add first class support for method forwarding

### ISSUE THREAD

**Issue by natebosch** [dart-lang/language#3748]
It's a common pattern to wrap an interface with a `Delegating` class which forwards all methods to a instance of the same interface and allows selectively overriding methods.

For example see  `Delegating*` classes in [package:collection](https://www.dartdocs.org/documentation/collection/1.14.3/collection/collection-library.html) and [package:async](https://www.dartdocs.org/documentation/async/1.13.3/async/async-library.html)

It would be cool if this was automatic rather than needing to manually write these classes.

Here's a straw man proposal:

```dart
abstract class SomeInterface {
  String someMethod();
  int someOtherMethod();
}

class Foo implements SomeInterface {
  final delegate SomeInterface _delegate;
  Foo(this._delegate);

  @override
  String someMethod() => 'Foo implementation';

  // Implicitly:
  // int someOtherMethod() => _delegate.someOtherMethod();
}
```

If:
- a field is marked `delegate`
- The delegate field is statically determined to be of type `Foo`
- The class `implements Foo`

Then:
- Any methods in `Foo` which are not directly implemented in the class are automatically implemented by forwarding to the field marked `delegate`.

I think this also could work with multiple delegates and it would be a static error to have a method with identical signatures in two interfaces with ambiguous forwarding. This is similar to a static error when implementing two interfaces with the same method and conflicting signatures.

```dart
class Foo implements First, Second {
  final delegate First _first;
  final delegate Second _second;
  Foo(this._first, this._second);
}
```

**Comment by FMorschel** [comment]
Since this came up recently and the last comment here is from more than 6 years ago, any status update on going towards this or similar? Like, anything in the language has changed so this is easier or harder to accomplish.

Thank you in advance for taking the time to answer.

**Comment by natebosch** [comment]
I think extension types probably help in many cases. I don't think they solve the problem fully because they are only a static feature - I cannot pass my `Foo` as if it were a `SomeInterface` to other code if `Foo` is an extension type.

**Comment by FMorschel** [comment]
I'm not sure this is the right place for me to inform you of this, but in #3747 I was talking about creating a `DelegatingFocusNode` class. I've fully forwarded all 48 methods/getters and setters to an existing `FocusNode` with it.

<details>

<summary> Here is the code </summary>

```dart
class DelegatingFocusNode implements FocusNode {
  DelegatingFocusNode({
    String? debugLabel,
    // ignore: deprecated_member_use, api needed
    FocusOnKeyCallback? onKey,
    FocusOnKeyEventCallback? onKeyEvent,
    bool skipTraversal = false,
    bool canRequestFocus = true,
    bool descendantsAreFocusable = true,
    bool descendantsAreTraversable = true,
  }) : _base = FocusNode(
          canRequestFocus: canRequestFocus,
          debugLabel: debugLabel,
          descendantsAreFocusable: descendantsAreFocusable,
          descendantsAreTraversable: descendantsAreTraversable,
          // ignore: deprecated_member_use, api needed
          onKey: onKey,
          onKeyEvent: onKeyEvent,
          skipTraversal: skipTraversal,
        );

  DelegatingFocusNode.fromClass(this._base);

  final FocusNode _base;

  @override
  bool get canRequestFocus => _base.canRequestFocus;

  @override
  set canRequestFocus(bool value) => _base.canRequestFocus = value;

  @override
  String? get debugLabel => _base.debugLabel;

  @override
  set debugLabel(String? value) => _base.debugLabel = value;

  @override
  bool get descendantsAreFocusable => _base.descendantsAreFocusable;

  @override
  set descendantsAreFocusable(bool value) =>
      _base.descendantsAreFocusable = value;

  @override
  bool get descendantsAreTraversable => _base.descendantsAreTraversable;

  @override
  set descendantsAreTraversable(bool value) =>
      _base.descendantsAreTraversable = value;

  @override
  // ignore: deprecated_member_use, api needed
  FocusOnKeyCallback? get onKey => _base.onKey;

  @override
  // ignore: deprecated_member_use, api needed
  set onKey(FocusOnKeyCallback? value) => _base.onKey = value;

  @override
  FocusOnKeyEventCallback? get onKeyEvent => _base.onKeyEvent;

  @override
  set onKeyEvent(FocusOnKeyEventCallback? value) => _base.onKeyEvent = value;

  @override
  bool get skipTraversal => _base.skipTraversal;

  @override
  set skipTraversal(bool value) => _base.skipTraversal = value;

  @override
  void addListener(VoidCallback listener) => _base.addListener(listener);

  @override
  Iterable<FocusNode> get ancestors => _base.ancestors;

  @override
  FocusAttachment attach(
    BuildContext? context, {
    FocusOnKeyEventCallback? onKeyEvent,
    // ignore: deprecated_member_use, api needed
    FocusOnKeyCallback? onKey,
  }) =>
      // ignore: deprecated_member_use, api needed
      _base.attach(context, onKeyEvent: onKeyEvent, onKey: onKey);

  @override
  Iterable<FocusNode> get children => _base.children;

  @override
  bool consumeKeyboardToken() => _base.consumeKeyboardToken();

  @override
  BuildContext? get context => _base.context;

  @override
  List<DiagnosticsNode> debugDescribeChildren() =>
      _base.debugDescribeChildren();

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) =>
      _base.debugFillProperties(properties);

  @override
  Iterable<FocusNode> get descendants => _base.descendants;

  @override
  void dispose() => _base.dispose();

  @override
  FocusScopeNode? get enclosingScope => _base.enclosingScope;

  @override
  bool focusInDirection(TraversalDirection direction) =>
      _base.focusInDirection(direction);

  @override
  bool get hasFocus => _base.hasFocus;

  @override
  bool get hasListeners => _base.hasListeners;

  @override
  bool get hasPrimaryFocus => _base.hasPrimaryFocus;

  @override
  FocusHighlightMode get highlightMode => _base.highlightMode;

  @override
  FocusScopeNode? get nearestScope => _base.nearestScope;

  @override
  bool nextFocus() => _base.nextFocus();

  @override
  void notifyListeners() => _base.notifyListeners();

  @override
  Offset get offset => _base.offset;

  @override
  FocusNode? get parent => _base.parent;

  @override
  bool previousFocus() => _base.previousFocus();

  @override
  Rect get rect => _base.rect;

  @override
  void removeListener(VoidCallback listener) => _base.removeListener(listener);

  @override
  void requestFocus([FocusNode? node]) => _base.requestFocus(node);

  @override
  Size get size => _base.size;

  @override
  DiagnosticsNode toDiagnosticsNode({
    String? name,
    DiagnosticsTreeStyle? style,
  }) =>
      _base.toDiagnosticsNode(name: name, style: style);

  @override
  String toStringDeep({
    String prefixLineOne = '',
    String? prefixOtherLines,
    DiagnosticLevel minLevel = DiagnosticLevel.debug,
  }) =>
      _base.toStringDeep(
        prefixLineOne: prefixLineOne,
        prefixOtherLines: prefixOtherLines,
        minLevel: minLevel,
      );

  @override
  String toStringShallow({
    String joiner = ', ',
    DiagnosticLevel minLevel = DiagnosticLevel.debug,
  }) =>
      _base.toStringShallow(minLevel: minLevel, joiner: joiner);

  @override
  String toStringShort() => _base.toStringShort();

  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) =>
      _base.toString(minLevel: minLevel);

  @override
  Iterable<FocusNode> get traversalChildren => _base.traversalChildren;

  @override
  Iterable<FocusNode> get traversalDescendants => _base.traversalDescendants;

  @override
  void unfocus({UnfocusDisposition disposition = UnfocusDisposition.scope}) =>
      _base.unfocus(disposition: disposition);
}
```

</details>

And even with all this work I even got an error when using this `DelegatingFocusNode` inside a `TextFormField` with `autofocus` set to true.

Error:

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
Class 'FocusNodeTextController' has no instance getter '_parent'.
Receiver: Instance of 'FocusNodeTextController'
Tried calling: _parent

When the exception was thrown, this was the stack:
#0      DelegatingFocusNode._parent (package:custom_fields/src/focus_node_text_controller.dart:140:7)
focus_node_text_controller.dart:140
#1      FocusScopeNode.autofocus (package:flutter/src/widgets/focus_manager.dart:1368:14)
focus_manager.dart:1368
#2      EditableTextState.didChangeDependencies.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2883:34)
editable_text.dart:2883
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
binding.dart:1386
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1322:11)
binding.dart:1322
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
binding.dart:1169
```

So I believe as the language is now, some things can't be fully done by delegating manually to a base class and that is something to be considered IMO.
